version: 0.0
os: linux
files:
  - source: /portal-source
    destination: /home/ec2-user/portal

permissions:
  - object: /home/ec2-user/portal
    owner: ec2-user
    mode: 644
    type:
      - file
hooks:
  ApplicationStop:
    - location: /stop_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location : /start_server.sh
      timeout: 300
      runas: ec2-user
