name: github-action-practice

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v2
        uses: actions/checkout@v2

      - name: aws-actions/configure-aws-credentials@v1
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ap-northeast-2

      - name: Check Node v            # Node v 확인
        run: node -v

      - name: Install Dependencies    # 의존 파일 설치
        run: npm install

      - name: Build
        run: |
          
          npm run build

        shell: bash

      - name: s3 upload
        run: |
          aws s3 sync build s3://portal-static-web-hosting
